### ISSUE TITLE
Playing soundtrack doesn't seem to work.

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/LAI-Echo-App#100]
When an echo has been created, I can't re-play the soundtrack to validate that the transcription is correct.

Here is a recording.

https://user-images.githubusercontent.com/12861981/198301029-cdfe8b26-1c4b-4362-a18f-4832e554f630.mov

**Comment by alecmerdler** [comment]
@tchaton Are you able to reproduce this reliably? Also, can you provide the following info:
- Browser
- Operating System
- Mobile/Desktop

**Comment by alecmerdler** [comment]
@tchaton Are you still able to reproduce this issue?

**Comment by alecmerdler** [comment]
I'm going to close this issue as not reproducible.
